/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IRuleInterface extends ethers.utils.Interface {
  functions: {
    "BASE()": FunctionFragment;
    "DISCOUNT()": FunctionFragment;
    "calDiscount(address)": FunctionFragment;
    "verify(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "BASE", values?: undefined): string;
  encodeFunctionData(functionFragment: "DISCOUNT", values?: undefined): string;
  encodeFunctionData(functionFragment: "calDiscount", values: [string]): string;
  encodeFunctionData(functionFragment: "verify", values: [string]): string;

  decodeFunctionResult(functionFragment: "BASE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "DISCOUNT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calDiscount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;

  events: {};
}

export class IRule extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IRuleInterface;

  functions: {
    BASE(overrides?: CallOverrides): Promise<[BigNumber]>;

    DISCOUNT(overrides?: CallOverrides): Promise<[BigNumber]>;

    calDiscount(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    verify(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;
  };

  BASE(overrides?: CallOverrides): Promise<BigNumber>;

  DISCOUNT(overrides?: CallOverrides): Promise<BigNumber>;

  calDiscount(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  verify(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    BASE(overrides?: CallOverrides): Promise<BigNumber>;

    DISCOUNT(overrides?: CallOverrides): Promise<BigNumber>;

    calDiscount(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    verify(arg0: string, overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    BASE(overrides?: CallOverrides): Promise<BigNumber>;

    DISCOUNT(overrides?: CallOverrides): Promise<BigNumber>;

    calDiscount(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    verify(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    BASE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DISCOUNT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    calDiscount(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verify(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
