/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IFaucet, IFaucetInterface } from "../IFaucet";

const _abi = [
  {
    inputs: [],
    name: "drain",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "drainToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IFaucet__factory {
  static readonly abi = _abi;
  static createInterface(): IFaucetInterface {
    return new utils.Interface(_abi) as IFaucetInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFaucet {
    return new Contract(address, _abi, signerOrProvider) as IFaucet;
  }
}
