/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IHandlerEvents,
  IHandlerEventsInterface,
} from "../IHandlerEvents";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "PolygonBridged",
    type: "event",
  },
];

export class IHandlerEvents__factory {
  static readonly abi = _abi;
  static createInterface(): IHandlerEventsInterface {
    return new utils.Interface(_abi) as IHandlerEventsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IHandlerEvents {
    return new Contract(address, _abi, signerOrProvider) as IHandlerEvents;
  }
}
