/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { SubContract, SubContractInterface } from "../SubContract";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "addtwoContract",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "sub",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506102e5806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80632572311214610030575b600080fd5b61004361003e36600461015a565b610057565b604051901515815260200160405180910390f35b60006100846040518060600160405280602b8152602001610285602b913961007f8789610261565b6100f0565b6000846001600160a01b031684846040516100a09291906101f6565b6000604051808303816000865af19150503d80600081146100dd576040519150601f19603f3d011682016040523d82523d6000602084013e6100e2565b606091505b509098975050505050505050565b6101358282604051602401610106929190610206565b60408051601f198184030181529190526020810180516001600160e01b03166309710a9d60e41b179052610139565b5050565b80516a636f6e736f6c652e6c6f67602083016000808483855afa5050505050565b600080600080600060808688031215610171578081fd5b853594506020860135935060408601356001600160a01b0381168114610195578182fd5b9250606086013567ffffffffffffffff808211156101b1578283fd5b818801915088601f8301126101c4578283fd5b8135818111156101d2578384fd5b8960208285010111156101e3578384fd5b9699959850939650602001949392505050565b8183823760009101908152919050565b6040815260008351806040840152815b818110156102335760208187018101516060868401015201610216565b818111156102445782606083860101525b50602083019390935250601f91909101601f191601606001919050565b60008282101561027f57634e487b7160e01b81526011600452602481fd5b50039056fe7375622e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2ea264697066735822122075f6cfc7a50a48fbed5a524bb5df0b2373bce3156bc90c1dc44c0fceb1cfc72064736f6c63430008040033";

export class SubContract__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<SubContract> {
    return super.deploy(overrides || {}) as Promise<SubContract>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): SubContract {
    return super.attach(address) as SubContract;
  }
  connect(signer: Signer): SubContract__factory {
    return super.connect(signer) as SubContract__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SubContractInterface {
    return new utils.Interface(_abi) as SubContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SubContract {
    return new Contract(address, _abi, signerOrProvider) as SubContract;
  }
}
